### PR TITLE
WIP: Python 3 compatibility

### PR DESCRIPTION
**Pull request by jleclanche**
Couldn't get further because I'm getting `'DatabaseWrapper' object has no attribute 'Database'` on setup.

### CODE REVIEW

**Comment by jleclanche** [comment]
ping

**Comment by ipmb** [comment]
Could you provide more information?

* Python version
* Exact command you are trying to run
* the full traceback

**Comment by jleclanche** [comment]
@ipmb more information for what? These are python 3 fixes

**Comment by ipmb** [comment]
Your pull request says:

> Couldn't get further because I'm getting 'DatabaseWrapper' object has no attribute 'Database' on setup.

Is this ready to merge or is there still an issue related to this?

**Comment by ipmb** [comment]
Also, please add the supported Python 3 versions to `.travis.yml` so we can get it in the testing matrix.

**Comment by jleclanche** [comment]
@ipmb it's ready to merge, but I don't think it completes the job.

**Comment by jleclanche** [comment]
@ipmb Rebased and testing on travis.

**Comment by ipmb** [comment]
Thanks for getting this started. I'd love to have botbot running on Python 3. Unfortunately, I don't have a ton of time to look into this at the moment. I'll leave this open if somebody else wants to pick it up and finish it.

**Comment by jleclanche** [comment]
The commits should be mergeable as-is; they don't complete 3.x compatibility but they don't harm 2.x compatibility either. Up to you of course.

**Pull request closed without merging**
